apiVersion: v1
kind: ConfigMap
metadata:
  name: kip-provider-config
  labels:
    app: kip-provider
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  NACOS_SERVER_ADDR: "10.42.0.125:8848"
  NACOS_NAMESPACE: "74a3fe73-35c1-474e-ade8-9bc460b3f398"
  NACOS_GROUP: "K8S_POC"
  NACOS_CONFIG_ENABLED: "true"
  NACOS_DISCOVERY_ENABLED: "false"
  NACOS_REGISTER_ENABLED: "false"
  NACOS_AUTO_REGISTRATION_ENABLED: "false"
  LOGGING_KAFKA_TOPIC: "kip-provider-log-k8s"
