apiVersion: v1
kind: ConfigMap
metadata:
  name: kip-provider-config
  labels:
    app: kip-provider
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR: "10.42.0.125:8848"
  SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: "10.42.0.125:8848"
  SPRING_CLOUD_NACOS_CONFIG_NAMESPACE: "public"
  SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE: "public"
  SPRING_CLOUD_NACOS_CONFIG_GROUP: "DEFAULT_GROUP"
  SPRING_CLOUD_NACOS_DISCOVERY_GROUP: "DEFAULT_GROUP"
  SPRING_CLOUD_SENTINEL_TRANSPORT_DASHBOARD: "10.42.0.125:8090"
  SPRING_CLOUD_SENTINEL_TRANSPORT_PORT: "8718"
