apiVersion: v1
kind: Secret
metadata:
  name: kip-provider-secret
  labels:
    app: kip-provider
type: Opaque
stringData:
  MYSQL_URL: "jdbc:mysql://10.42.0.124:3306/dev_provider?characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
  MYSQL_USERNAME: "dev_dba"
  MYSQL_PASSWORD: "replace-me"
